### ISSUE TITLE
no direct access to the source ids in vote events

### ISSUE THREAD

**Issue by michalskop** [KohoVolit/scraper-sk_nrsr#1]
There is no direct access to the source IDs ("3081") for vote events, e.g..
http://www.nrsr.sk/web/Default.aspx?sid=schodze/hlasovanie/hlasklub&ID=3081

"identifier" is used for something else

It is the only id people from outside can use to identify a vote event.

**Comment by girogiro** [comment]
Source IDs are present in `sources.url` field and can be queried by:
http://api.parldata.eu/sk/nrsr/vote-events?where={"sources.url":{"$regex":"ID=3081$"}}
or the whole `source.url` can usually be queried by to find a vote event. This is actually identifier+scheme packed to a single value.

See also:
https://docs.google.com/a/g.kohovolit.eu/document/d/1vWwa6fNoMlAXmWQSLcBTizDAeFvC19gg2uIluzwZ724/edit?pli=1#heading=h.g593t5u2l5fz
