### ISSUE TITLE
wrong date for vote event

### ISSUE THREAD

**Issue by michalskop** [KohoVolit/scraper-sk_nrsr#2]
http://www.nrsr.sk/web/Default.aspx?sid=schodze/hlasovanie/hlasklub&ID=3081
hs different date/time from
http://api.parldata.eu/sk/nrsr/vote-events/54d4ed4f273a391017dbcca2

which brings problems for memberships starting 1998-10-29 (beginning of the term)

**Comment by girogiro** [comment]
All datetimes in database are required to be in UTC. The value is correct but needs to be converted to local datetime. You may use _vpapi.timezone()_ and _vpapi.utc_to_local()_ functions and get the timezone name for the country from the API root endpoint.

**Comment by michalskop** [comment]
However - these are not consistent: date in vote event (1998-10-28T23:00:00) and date in memberships (1998-10-29)

**Comment by girogiro** [comment]
`Motion.date` and `VoteEvent.start_date` are of _datetime_ type, it is always a full date+time value and as such is a subject of timezone conversions.

`Membership.start_date/end_date` is of _partialdate_ type, ie. string that may contain a date or an incomplete date value, eg. "1998-10-29", "1998-10" (=sometimes in Oct 1998), "1998" (=sometimes in 1998).  There is no time information so no timezone conversion to apply.

Vote event value "1998-10-28T23:00:00" converted from UTC to local Europe/Bratislava timezone is "1998-10-29T00:00:00" which is OK with the membership date.

Popolo uses properties `date` and `*_date` a little bit ambiguously, sometimes it means the _partialdate_ type (Membership, Organization) and sometimes the _datetime_ type (Motion, VoteEvent, Speech).
